apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: startup-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      # 1. 로그인 서비스 (구체적인 경로를 반드시 위에 배치)
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: face-login-service
            port:
              number: 80

      # 2. 메인 상품 서비스 (루트 경로를 아래에 배치)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: product-search-service
            port:
              number: 80