apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: startup-ingress
spec:
  rules:
  - http:
      paths:
      - path: /  # 모든 요청을 허용
        pathType: Prefix
        backend:
          service:
            name: product-search-service # 내부 DNS 이름 사용
            port:
              number: 80