apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search-deployment
  labels:
    app: product-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-search
  template:
    metadata:
      labels:
        app: product-search
    spec:
      containers:
      - name: product-search
        image: docker.io/library/product-app:v1.1
        imagePullPolicy: Always
        command: ["uvicorn"]
        # app/ 폴더 내의 main.py 실행 (중요)
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "80"]
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: common-env
